services:
  server:
    image: docker.gitea.com/gitea:1.25-rootless
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - gitea_gitea-data-vol:/var/lib/gitea
      - gitea_gitea-config-vol:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - gitea_mysql-data-vol:/var/lib/mysql

volumes:
  gitea_gitea-data-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/mrodozov/Downloads/gitea/data
      o: bind
  gitea_gitea-config-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/mrodozov/Downloads/gitea/config
      o: bind
  gitea_mysql-data-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/mrodozov/Downloads/gitea/mysql
      o: bind