services:
  server:
    image: 
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      # Timezone settings
      - TZ=Europe/Sofia
    restart: always
    volumes:
      - gitea-data-vol:/var/lib/gitea
      - gitea-config-vol:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db
  db:
    image: leosantos/arm32v7-mysql:8.0.22
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - mysql-data-vol:/var/lib/mysql

volumes:
  gitea-data-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/alarm/Downloads/gitea_local_repos/gitea_workspace/data
      o: bind
  gitea-config-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/alarm/Downloads/gitea_local_repos/gitea_workspace/config
      o: bind
  mysql-data-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/alarm/Downloads/gitea_local_repos/gitea_workspace/mysql
      o: bind